// for UI
export const SET_HORIZONTAL_SPLIT_SIZE = 'SET_HORIZONTAL_SPLIT_SIZE';

// for settings
export const SET_FILE_SIZE_FORMAT = 'SET_FILE_SIZE_FORMAT';

// for local dir browsing
export const LOCAL_DIR_LOAD_REQUEST = 'LOCAL_DIR_LOAD_REQUEST';
export const LOCAL_DIR_LOAD_SUCCESS = 'LOCAL_DIR_LOAD_SUCCESS';
export const LOCAL_DIR_LOAD_FAILURE = 'LOCAL_DIR_LOAD_FAILURE';


// for FTP browsing
export const FTP_CONNECT_REQUEST = 'FTP_CONNECT_REQUEST';
export const FTP_CONNECT_SUCCESS = 'FTP_CONNECT_SUCCESS';
export const FTP_CONNECT_FAILURE = 'FTP_CONNECT_FAILURE';

export const FTP_DIR_LOAD_REQUEST = 'FTP_LOAD_DIR_REQUEST';
export const FTP_DIR_LOAD_SUCCESS = 'FTP_LOAD_DIR_SUCCESS';
export const FTP_DIR_LOAD_FAILURE = 'FTP_LOAD_DIR_FAILURE';

// for selecting files to download
export const FTP_DIR_TOGGLE_SELECTION = 'FTP_DIR_TOGGLE_SELECTION';
export const FTP_DIR_TOGGLE_ALL = 'FTP_DIR_TOGGLE_ALL';
export const FTP_DIR_SET_SELECTION = 'FTP_DIR_SET_SELECTION';

// for aria2c control
export const ARIA2C_START_REQUEST = 'ARIA2C_START_REQUEST';
export const ARIA2C_START_SUCCESS = 'ARIA2C_START_SUCCESS';
export const ARIA2C_START_FAILURE = 'ARIA2C_START_FAILURE';

// for Download
export const START_DOWNLOADS = 'START_DOWNLOADS';
export const ADD_DOWNLOAD_ITEM = 'ADD_DOWNLOAD_ITEM';
export const UPDATE_DOWNLOAD_ITEM = 'UPDATE_DOWNLOAD_ITEM';
export const REMOVE_DOWNLOAD_ITEM = 'REMOVE_DOWNLOAD_ITEM';
