// for UI
export const SET_HORIZONTAL_SPLIT_SIZE = 'SET_HORIZONTAL_SPLIT_SIZE';

// for settings
export const SET_FILE_SIZE_FORMAT = 'SET_FILE_SIZE_FORMAT';
export const SET_DOWNLOAD_SPLIT = 'SET_DOWNLOAD_SPLIT';


// for local dir browsing
export const LOCAL_DIR_LOAD_REQUEST = 'LOCAL_DIR_LOAD_REQUEST';
export const LOCAL_DIR_LOAD_SUCCESS = 'LOCAL_DIR_LOAD_SUCCESS';
export const LOCAL_DIR_LOAD_FAILURE = 'LOCAL_DIR_LOAD_FAILURE';


// for FTP browsing
export const FTP_CONNECT_REQUEST = 'FTP_CONNECT_REQUEST';
export const FTP_CONNECT_SUCCESS = 'FTP_CONNECT_SUCCESS';
export const FTP_CONNECT_FAILURE = 'FTP_CONNECT_FAILURE';

export const FTP_DIR_LOAD_REQUEST = 'FTP_LOAD_DIR_REQUEST';
export const FTP_DIR_LOAD_SUCCESS = 'FTP_LOAD_DIR_SUCCESS';
export const FTP_DIR_LOAD_FAILURE = 'FTP_LOAD_DIR_FAILURE';

// for selecting files to download
export const FTP_DIR_TOGGLE_SELECTION = 'FTP_DIR_TOGGLE_SELECTION';
export const FTP_DIR_TOGGLE_ALL = 'FTP_DIR_TOGGLE_ALL';
export const FTP_DIR_SET_SELECTION = 'FTP_DIR_SET_SELECTION';

// for downloader control
export const INIT_DOWNLOADER_REQUEST = 'INIT_DOWNLOADER_REQUEST';
export const INIT_DOWNLOADER_SUCCESS = 'INIT_DOWNLOADER_SUCCESS';
export const INIT_DOWNLOADER_FAILURE = 'INIT_DOWNLOADER_FAILURE';

// for downloads
export const START_DOWNLOADS = 'START_DOWNLOADS';
export const UPDATE_DOWNLOAD_QUEUE = 'UPDATE_DOWNLOAD_QUEUE';
